### ISSUE TITLE
New Commerce Events

### ISSUE THREAD

**Issue by lukeholder** [craftcms/legacy-commerce-docs#37]
New events to be documented: https://github.com/craftcms/commerce/commit/7baba4a3742747152957dd0e91d2c980b1807640

**Comment by lukeholder** [comment]
Similar exisiting events already existed:
```
EVENT_AFTER_ADD_LINE_ITEM
EVENT_AFTER_REMOVE_LINE_ITEM
```
These are when the line items are removed from the order in memory (no persisted to DB yet)

new events are
```
EVENT_AFTER_APPLY_ADD_LINE_ITEM
EVENT_AFTER_APPLY_REMOVE_LINE_ITEM
```
These are when the line items are removed from the order in the DB

**Comment by lukeholder** [comment]
Will be in next commerce release.

**Comment by nfourtythree** [comment]
New event being added in `3.2` `DEFINE_ADDRESS_LINES` related to: https://github.com/craftcms/commerce/issues/1305

**Comment by lukeholder** [comment]
All these changes have been copied to the new repo: https://github.com/craftcms/docs/pull/28
